skeiya/ProjectsTM

TaskManagement/Service/ContextMenuService.cs, TaskManagement/Service/FilterComboBoxService.cs, TaskManagement/TaskManagement.csproj, TaskManagement/UI/MainForm.cs, TaskManagement/UI/WorkItemGrid.cs
MainFormが大きくなってきていたので、分離できそうな個所を別クラスに切り出した。
次は、WorkItemGridをやるつもり。
=> Refactoring

TaskManagement/UI/SearchWorkitemForm.Designer.cs, TaskManagement/UI/SearchWorkitemForm.cs
ブランチ分離するの忘れてて2つのタスクが1つのプルリクになっちゃいました。。。
=> 検索結果での備考の表示に対応＆検索結果にマイルストーンを表示するオプションを追加。

TaskManagement/TaskManagement.csproj, TaskManagement/UI/MainForm.Designer.cs, TaskManagement/UI/MainForm.cs, TaskManagement/UI/VersionForm.Designer.cs, TaskManagement/UI/VersionForm.cs, TaskManagement/UI/VersionForm.resx
=> バージョン情報表示に対応。

TaskManagement/Model/TaskState.cs
期日の制約が厳密ではないタスクを表す状態を追加。
期日超過チェック等の処理から対象外とするために使用する予定。
=> 作業項目の状態にBackgoundを追加。

FreeGridControl/FreeGridControl.csproj, FreeGridControl/GridControl.cs, FreeGridControl/RowColRange.cs, ProjectsTM/ProjectsTM.csproj, ProjectsTM/Service/WorkItemEditService.cs, ProjectsTM/UI/HeightAndWidthCalcultor.cs, ProjectsTM/UI/MainForm.Designer.cs, ProjectsTM/UI/MainForm.cs, ProjectsTM/UI/PenCache.cs, ProjectsTM/UI/TaskListForm.Designer.cs, ProjectsTM/UI/TaskListForm.cs, ProjectsTM/UI/TaskListForm.resx, ProjectsTM/UI/TaskListGrid.Designer.cs, ProjectsTM/UI/TaskListGrid.cs, ProjectsTM/UI/TaskListItem.cs, ProjectsTM/UI/WorkItemGrid.cs, ProjectsTM/ViewModel/ViewData.cs
大体できた。
既存の検索からの機能は移行期間は残しておいて、後々削除しようと思う。
=> 編集メニューからタスクリスト起動に対応

FreeGridControl/Cache.cs, ProjectsTM/UI/MainForm.cs, ProjectsTM/UI/TaskListGrid.cs, ProjectsTM/UI/WorkItemGrid.cs, ProjectsTM/ViewModel/ImageBuffer.cs, ProjectsTM/ViewModel/ViewData.cs
間違って、fix_crashの後ろにコミットを積んでしまった。
=> タスクリストの見た目を微調整。

ProjectsTM.UI.MainForm/FilterForm.Designer.cs, ProjectsTM.UI.MainForm/FilterForm.cs
フィルタ設定フォーム上の
「マイルストンフィルタの検索結果の表示」
があまり使われそうではなかったので、削除。
=> マイルストンフィルタの検索結果の表示を削除

ProjectsTM.UI.TaskList/TaskListGrid.cs
もともと複数選択をする関数があったので
その関数を使いまわして実現しました。
またkey downイベントでCtr+Aでその関数が呼ばれるようにしました。
=> タスクリストでCtr+A(全項目選択)を追加

ProjectsTM.UI.MainForm/MainForm.Designer.cs
2b57d5f4f64e461baf5a54c657acdea16155be62
変更内容的にDesigner.csの修正は不要なはずなので、元に戻しました。
=> ↓このコミットでの変更により、スクロールバーの幅が狭くなってしまっていました。

ProjectsTM.Service/FilterComboBoxService.cs, ProjectsTM.UI.MainForm/FilterForm.cs, ProjectsTM.ViewModel/Filter.cs
・過去バージョン互換のために残していたHideMembersを削除
・HideMembers→ShowMembers変換処理を削除
=> 過去バージョン互換のために残していたHideMembersを削除

FreeGridControl/GridControl.cs
■ マウスの左右スクロールでの水平スクロールは難しかったためお題目変更しました。
■ FreeGridControlのMouseWheelイベントにShift＋縦スクロールで水平にスクロールする機能を追加しました。
=> 縦shift+スクロールで水平スクロールできる機能を追加しました。

ProjectsTM.Model/CallenderDay.cs, ProjectsTM.UI.MainForm/WorkItemGrid.cs
日付が飛んでいるときの計算不正を修正。
不要になったメソッドも削除した。
=> 貼り付け時の不具合修正

FreeGridControl/RowColRange.cs, ProjectsTM.Model/CallenderDay.cs, ProjectsTM.Model/WorkItem.cs, ProjectsTM.Service/DrawService.cs, ProjectsTM.Service/KeyAndMouseHandleService.cs, ProjectsTM.UI.MainForm/WorkItemGrid.cs, ProjectsTM.ViewModel/IWorkItemGrid.cs
Selected状態でなくてもマウスオーバー時は枠を強調表示するようにした。
タスクがない場所でも、どのセルが選択状態なのかわかりやすくした
=> マウスオーバー時の色強調表示

ProjectsTM.UI.Common/EazyRegexForm.Designer.cs, ProjectsTM.UI.MainForm/ManagementWokingDaysForm.Designer.cs, ProjectsTM.UI.MainForm/ManagementWokingDaysForm.cs, ProjectsTM.UI.MainForm/WorkItemGrid.cs, ProjectsTM.ViewModel/ViewData.cs
■稼働に設定
・複数削除処理実装
・日付入力をDateTimePickerに変更
・連続日数同時追加機能実装
■WorkItemGrid
・タブキーでのアイテム切り替え実装
=> 稼働日設定改良、タブキーでのアイテム切り替え

ProjectsTM.UI.TaskList/TaskListGrid.cs
=> タスクリストが開けないことがある不具合修正

ProjectsTM.UI.MainForm/WorkItemGrid.cs, UnitTest/UnitTestProject/KeyAndMouseHandlerTest.cs, UnitTest/UnitTestProject/UnitTestProject.csproj
マウス操作の単体テストを一通り追加してから、リファクタリングや機能改善を行う。
土台固め。
=> マウス操作がデグレードしやすいので単体テストを作成。

ProjectsTM.UI.MainForm/WorkItemGrid.cs, ProjectsTM.ViewModel/ViewData.cs
・Tabキー以外でもタスク遷移に反応してしまっていたバグを修正
・ソートしたデータに対してタスク移動するように修正
=> Tabキーによるタスク遷移改善

ProjectsTM.UI.MainForm/MainForm.Designer.cs, ProjectsTM.UI.MainForm/MainForm.cs, ProjectsTM.UI.MainForm/ManageMySettingForm.Designer.cs, ProjectsTM.UI.MainForm/ManageMySettingForm.cs, ProjectsTM.UI.MainForm/ManageMySettingForm.resx, ProjectsTM.UI.MainForm/ProjectsTM.UI.MainForm.csproj, ProjectsTM.UI.MainForm/WorkItemGrid.cs, ProjectsTM.ViewModel/UserSetting.cs
・管理メニューに「個人設定」フォームを追加。自分がだれかを設定する。
・設定されたユーザ名はUserSettingクラスで保存するよう追加
・起動時に今日の自分へ自動的にスクロールされるよう追加
=> 設定で自分がだれかを覚えるようにし、起動時に今日の自分が自動的に表示領域になるようスクロールする。

ProjectsTM.Model/MembersWorkItems.cs, ProjectsTM.UI.MainForm/MainForm.Designer.cs, ProjectsTM.UI.MainForm/MainForm.cs, ProjectsTM.UI.MainForm/ProjectsTM.UI.MainForm.csproj, ProjectsTM.UI.MainForm/TrendChart.Designer.cs, ProjectsTM.UI.MainForm/TrendChart.cs, ProjectsTM.UI.MainForm/TrendChart.resx
・管理メニューへ　「総工数トレンド」を追加
・プロジェクトごとに総工数のトレンドグラフを表示するフォーム追加
仕様も含め何かあればください。
=> 総工数のトレンドグラフを表示するUI追加

ProjectsTM.Model/AbsentInfo.cs, ProjectsTM.Service/DrawService.cs
AbsentInfoに登録されている期間をグレーで描画する処理を追加
=> 不在期間の背景色をグレーにする処理を追加

ProjectsTM.Service/WorkItemEditService.cs, ProjectsTM.UI.TaskList/ProjectsTM.UI.TaskList.csproj, ProjectsTM.UI.TaskList/TaskListContextMenuHandler.cs, ProjectsTM.UI.TaskList/TaskListForm.cs, ProjectsTM.UI.TaskList/TaskListGrid.cs
■　TaskListContextMenuHandlerを追加。
・　状態をDoneに変える。
・　状態変えたら再描画。
■　TaskListFormにメンバTaskListContextMenuHandlerを追加。
私は、あとはこの系から削除できてもいいかなぁくらいに思っています。
ほかに何かしたいことありますでしょうか？
=> タスクリストの右クリックメニュー対応

ProjectsTM.Service/CalculateSumService.cs, ProjectsTM.Service/DrawService.cs, ProjectsTM.Service/KeyAndMouseHandleService.cs, ProjectsTM.Service/ToolTipService.cs, ProjectsTM.Service/WorkItemEditService.cs, ProjectsTM.UI.MainForm/MainForm.cs, ProjectsTM.UI.MainForm/RowColResolver.cs, ProjectsTM.UI.MainForm/WorkItemGrid.cs, ProjectsTM.UI.TaskList/TaskListGrid.cs, ProjectsTM.ViewModel/FilteredItems.cs, ProjectsTM.ViewModel/ProjectsTM.ViewModel.csproj, ProjectsTM.ViewModel/ViewData.cs
・FilterItems.cs：FilteredItemsの追加, Filterを適用したモデルへのアクセスはここに集めた
・ViewData.cs：Filter更新時とAppData更新時に、FilterItemsを更新するよう追加
・その他：FilterdItemsでアクセスするよう修正
=> Filterを適用したモデルへのアクセスを担当するFilteredItemsクラスを追加

ProjectsTM.Service/KeyAndMouseHandleService.cs, ProjectsTM.Service/ToolTipService.cs, ProjectsTM.UI.Main/WorkItemGrid.cs, UnitTest/UnitTestProject/KeyAndMouseHandlerTest.cs
=> ツールチップの更新が何度もかかる問題を修正。
