skeiya/ProjectsTM

TaskManagement/UI/WorkItemGrid.cs
_drawService及び、その内部のインスタンスがDisposeされずに次のインスタンスが生成されてメモリ不足になっていたことが原因と思われる。）
=> 高速に拡大縮小等を繰り返すと落ちることがある問題を修正。（

ProjectsTM/ViewModel/ViewData.cs
概要
　RemoveFreeTimeMembers()の呼び出し元のGetFilterMember()は、
　色々な所から呼び出しているため、ここで少し重い処理をすると何倍にもなって効いてくる。
　RemoveFreeTimeMembers()　→　AddFreeTimeMembersToHideMembers()と関数名変更し、
　フィルターが反映されるタイミングでfreeTimeMembersをHideMembersへ自動追加するよう変更する。
　
　この変更により、
　　freeTimeMembersを表示させたい時は、フィルタ設定ダイアログにて、
　　　1、[タスクがないメンバーを表示する]チェックボックス をONする
　　　2,   表示したいfreeTimeMemberのチェックボックスをONする
　　の2段階操作が必要になる
　という仕様変更が生じる。
遅かった要因詳細
　private IEnumerable<Member> RemoveFreeTimeMembers(IEnumerable<Member> members) 
　内の
　return members.Where(m => GetFilteredWorkItemsOfMember(m).HasWorkItem(Filter.Period));
　にて
　Original.WorkItemsのSortedDictionaryから全てのメンバーの WorkItemsを順番に取り出すところが遅かったよう。
=> タスクがないメンバー非表示チェックボックスを有効にすると遅くなる問題を修正

ProjectsTM/UI/SearchWorkitemForm.Designer.cs, ProjectsTM/UI/SearchWorkitemForm.cs
・検索結果をCSVへこぴぺしやすいよう検索結果グリッドの複数選択に対応
・上記に伴い、検索結果グリッド選択で発生するイベント、関数では、「選択行数が1行か」を判定するように変更
=> 検索結果をCSVへコピペしやすいよう複数選択に対応

FreeGridControl/GridControl.cs
_viewData.Selectが変更されると、WorkItemGridとTaskGridの再描画が行われるが、
その際に走る
WorkItemGrid.MoveVisibleRowCol(RowIndex row, ColIndex col)　内の
Thread.Sleep(250);が効いていた。
このThread.Sleep(250);は、グリッド外ドラッグによる高速移動を抑制するためのWaitであったが、
その対策によって失っているもの方が大きいので、対策をやめる。
タスクリストの選択描画改善を優先する。
=> タスクリストの選択描画が遅い問題の修正

InnoSetupScripts.iss, ProjectsTM.Logic/KeyState.cs, ProjectsTM.UI.TaskList/TaskListGrid.cs
※　プロジェクト構成リファクタブランチへのPRです。
■　タスクリスト上検索結果のコピペのために、タスクリスト項目を複数選択できるよう変更。
・前回選択された行数を覚えるメンバを追加
・シフトキーが押されたことを検出するイベントを追加
・シフトキー押されながら項目クリックしたときは、
　前回選択項目から、現在選択項目の間の項目すべてを_viewData.Selectedに追加するよう変更
=> タスクリスト上で項目を複数選択できるよう追加＋選択項目をCtrl＋Cでコピーできるよう追加

ProjectsTM.Model/MembersWorkItems.cs, ProjectsTM.Model/WorkItems.cs, ProjectsTM.Service/AppDataFileIOService.cs
■問題
WorkItemが編集されると（編集前Itemは削除して）新しいWorkItemが追加される設計のため、
AppDataファイル上ではMemberごとのWorkItemsの最後尾にworkItemが追加されることになり、
マージ時に適切な差分検出ができず、非編集箇所の変更差分が多く検出される。
■対策
AppDataファイル出力時にMemberごとのWorkItemsをPeriod.Fromでソートすることで、
マージ検出時に非編集箇所が検出されることを抑制する。
=> AppDataをファイル出力時に、メンバー内タスクをPeriod.fromでソートするよう追加。（AppDataファイルのマージ簡易にするため）

ProjectsTM.Model/AppData.cs, ProjectsTM.Model/Members.cs, ProjectsTM.Service/FilterComboBoxService.cs, ProjectsTM.UI.MainForm/FilterForm.cs, ProjectsTM.ViewModel/Filter.cs, ProjectsTM.ViewModel/ViewData.cs
・今のフィルター定義は「何を隠すか」という意味でHideMemberesとしていたが、
「何を見せるか」という意味のShowMembersへ変更
・過去バージョンフィルタを読んだ際は、HideMembersがShowMembersへ変換されるよう追加。過去バージョンで作られたフィルターは、全てインポート•エクスポートすれば、変換可能
=> 新規メンバーを追加した際に、全てのフィルターで表示されないようにする

ProjectsTM.ViewModel/ViewData.cs
元の実装だと、ALLフィルタが初期値（Filter.All(null)）であった場合にしか、
ALLフィルタを更新（ShowMembersを更新）できない。
そのため、
二回目のAppDataセット時（別の日程表ファイルを開いた時など）のALLフィルタは
ひとつ前のAppDataによって作成されたALLフィルタとなってしまう。
AppDataをセットする際は常に
新しいALLフィルタへ更新するよう修正する。
=> 二回目のAppDataセット時にALLフィルタが更新されない問題を修正

ProjectsTM.Model/WorkItem.cs
new WorkItem( )された際にTaskStateがNew(仕様削除した状態)になってしまう問題を修正。
WorkItem._stateが初期化されていないので、enumの初期値であるNew(仕様削除した状態)になってしまっていた。
これにより、「作業項目の追加ダイアログ」でcomboBoxState.SelectedItemにNewがセットされてしまっていた。
=> new WorkItem( )した際にTaskStateがNew(仕様削除した状態)になってしまう問題を修正。

ProjectsTM.UI.TaskList/TaskListForm.cs
TaskListFormの下部分に出る人月単位の工数を小数第一位まで表示するように変更しました。
=> TaskListFormの下部分に出る人月単位の工数を小数第一位まで表示

ProjectsTM.Service/CountMemberNumService.cs, ProjectsTM.Service/ProjectsTM.Service.csproj, ProjectsTM.UI.MainForm/ManageMemberForm.Designer.cs, ProjectsTM.UI.MainForm/ManageMemberForm.cs
■ DLG内に合計人数や各所属人数を表示するためのlavelを追加
■ ProjectTM.Serviceに合計人数や各所属人数を数えて文字列で渡すクラスCountMemberNumServiceを追加
■ 表示、編集、追加のタイミングで表示文字列が変更されるようにManageMemberFormを変更
◆追加ボタンにアンカーがついていないバグがあったのでついでに修正。
@松蔭さん
退社済み属性の対応はまだマージされていないのでしょうか？
#22がClose?されていた、Memberクラスにそのようなプロパティがなかったこと
からそのように思ってます。
=> メンバーの編集画面で、全メンバー数や各所属ごとの人数を表示するように対応しました。

ProjectsTM.UI.TaskList/TaskListForm.cs
=> タスクリストで更新ボタンをクリックすると、調整した列幅が調整前に戻ってしまう問題を修正

ProjectsTM.UI.MainForm/ManageMemberForm.cs
編集後にリスト更新がかかっていなかったので、
更新するよう修正
=> メンバー編集ダイアログのDownボタンでメンバ並び順を変更しても、ダイアログ上のリストへ変更が反映されない問題を修正

ProjectsTM.Service/FilterComboBoxService.cs, ProjectsTM.UI.MainForm/FilterForm.cs, ProjectsTM.ViewModel/Filter.cs, ProjectsTM.ViewModel/ViewData.cs
■ViewData.cs
・SetAppData( )内のALLフィルタ更新を、ALLフィルタ設定時のみ更新するよう修正
　（常にALLフィルタの更新していた。
　　ALLフィルタ設定時は、showMembersを更新する必要があるため、
　　ALLフィルタ設定時の更新は残す）
■Filter.cs
・「ViewData.Filterに設定されたフィルタが、ALLフィルタとして設定されたものか」
　を識別するフラグ（IsAllFilter）を追加。これをコンストラクタの引数に追加
■その他ファイル
・Filterコンストラクタの変更へ追従
　
=> リロードするとAllフィルタに切りわかってしまう問題を修正

ProjectsTM.UI.TaskList/ColDefinition.cs, ProjectsTM.UI.TaskList/ColIds.cs, ProjectsTM.UI.TaskList/ColSpecification.cs, ProjectsTM.UI.TaskList/ProjectsTM.UI.TaskList.csproj, ProjectsTM.UI.TaskList/TaskListGrid.cs
列幅自動調整列は右端にしないと、列幅変更中の自動更新が整合性取れないので、備考列を右端に変更。
それに伴い、列定義関連の実装を整理。
=> タスクリストの列順を変更

ProjectsTM.Service/FormSizeRestoreService.cs, ProjectsTM.UI.MainForm/MainForm.cs
■ FormSizeRestoreServiceにメソッド追加
　LoadLastTimeFormState
->前回の終了時のWIndowStateを読みだす。
　SaveFormState
->終了時のWindowStateを保存
■ MainFormの初期サイズ決定ロジックを変更
　　前回サイズがMaxmizedならそれを再現、Normalなら閉じたときのサイズを再現。
=> 前回終了時が最大化状態だったら復元する機能を追加しました。

ProjectsTM.UI.TaskList/TaskListGrid.cs
■ TaskListGridにマウスDownした位置保持するメンバ追加(_mouseDownPoint)
■ マウスDownした位置とマウスUpした位置の距離を計算するメソッド追加(CalcDistance)
■ DownとUPの距離がMAX_SORTABLE_DISTANCE以内の場合のみソートリクエストを出すように変更
=> タスクリストのタイトル領域でマウスDownとマウスUPが一定距離内の時のみソートするするように改善

ProjectsTM.Service/KeyAndMouseHandleService.cs, ProjectsTM.Service/ToolTipService.cs
マイルストーンが見にくい問題の対策。
マイルストーンへマウスオーバしたときに、マイルストーンをツールチップ表示するよう追加。
同一日に複数マイルストン存在する場合は、複数行表示。
★対策として足りなそうであれば、別案試すので、教えてください。
=> マイルストーンにマウスオーバしたときに、マイルストンをツールチップに表示するよう追加

ProjectsTM.UI.TaskList/TaskListGrid.cs, ProjectsTM.UI.TaskList/TaskListItem.cs, ProjectsTM.ViewModel/ViewData.cs
■ TaskListGridでMSの行をダブルクリックするとEditMileStoneFormを呼ぶように変更。
クリックしたMSを特定するロジックは同じプロジェクト内で同じ名前のMSはない。
　このロジックで対象のMSを取得する。TaskListGridの253行目。
■ EditMileStoneFormで編集後元データ(viewData.Original)を編集後のMSと置換。
　
■ Grid内のデータも書き直す。
=> タスクリストでMSをダブルクリックから編集可能にする対応

ProjectsTM.UI.TaskList/ColDefinition.cs
■ ColDefinition.Sortを変更
ソート列がエラーの時だけ逆向きでソートするようにした。
=> taskListのエラーソートを逆にする対応

ProjectsTM.Service/GitCmdRepository.cs, ProjectsTM.Service/GitRepositoryService.cs
users/matsukage/toolTipHistoryへのプルリクです。
=> 最終更新者名が日本語の場合に文字化けする問題を修正。最終更新者名に丸括弧が表示されてしまう問題を修正
